### ISSUE TITLE
MySQL access denied (Mac OS)

### ISSUE THREAD

**Issue by ilyar** [ilyar/umi-project-stub#7]
## Окружение

OS: Mac OS

## Подробности

>  Произошла ошибка во время выполнения запроса к серверу. Это я устанавливаю в бд, установленную с помощью homebrew. А которая в ВМ не пускает с начальными значениями в документации, то есть там "логин/пароль неверный"
>  а если точнее, то в mysql access denied https://toster.ru/q/407727#comment_1368291

**Comment by ghost** [comment]
@ilyar когда я поднимал mysql на OSX, я в терминале ввёл mysql_secure_installation, и все доступы настроил. А с юми всё равно ошибка - access denied (using password: YES) при входе в mysql с паролем, и access denied (using password: NO) без ввода пароля. Это ошибка 28000. Установка с базовыми значениями не работает, там не может соединиться с БД

**Comment by ilyar** [comment]
После выполнения `vagrant up` при настройки виртуальной машины база данный и пользователь создаются:
```
host: localhost
user: umi
password: umi
dbname: umi
``` 

Пароль для root: `local`.

**Comment by ghost** [comment]
[Скрин 1](http://i.imgur.com/lKknoCq.png)
[Скрин 2](http://i.imgur.com/zcc3TIO.png)

ВМ запущена, захожу по  localhost, SSH работает

**Comment by ilyar** [comment]
На скринах не правильный домен, вероятно вы путаете установленные сервисы на основной машине и на виртуальной. Использование ВМ подразумевает, что на основной не обязательно иметь сервисы базы данных и веб-сервера.

Попробуйте обратиться домену `http://project_name_dir.local/`, где `project_name_dir` название папки из корой поднимается ВМ.

**Comment by ghost** [comment]
Папка с проектом находится в `/Volumes/Работа/webdev/umi/`. Туда же писал `vagrant up`. Пробую обратиться к домену `http://umi.local/` - DNS не найден

**Comment by ilyar** [comment]
Вероятно нет плагина из необходимых зависимостей. Что говорит команда `vagrant plugin list`?

**Comment by ilyar** [comment]
Если проблема именно в плагине, то решение:

    vagrant plugin install vagrant-hostmanager
    cd /Volumes/Работа/webdev/umi/
    vagrant reload --provision

**Comment by ghost** [comment]
вот,  теперь всё отлично)

**Comment by ilyar** [comment]
Замечательно, пользуйтесь, буду рад предложениям и вопросам.
